name: 🐞 Bug report
description: Create a bug report
title: "[BUG]: "
labels: ["bug", "needs triage"]
body:
  - type: input
    attributes:
      label: Company
      description: The company which owns the Reveal SDK license.
    validations:
      required: true
  - type: input
    attributes:
      label: SDK Version
      description: Version of the Reveal SDK the bug was found.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Client Framework
      description: What JavaScript framework is this bug affecting?
      options:
        - Angular
        - HTML/JavaScript
        - React
        - ASP.NET Web App
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Server Platform
      description: What server platform is this bug affecting?
      options:
        - ASP.NET
        - Node.js
        - Java
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please give us a detailed description of the issue that you're seeing. You can add screenshots and videos as well.
      placeholder: Tell us what you see!
    validations:
      required: true

