blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/RevealBi/Reveal.Sdk/discussions/category_choices
      about: Please ask questions for Reveal SDK here.
    - name: Read the Docs
      url: https://help.revealbi.io/
      about: Be sure you've read the docs!
    - name: Join us on Discord
      url: https://discord.gg/Ped3sSK5Xw
      about: Join our Discord community

